#!/usr/bin/env python

from scription import Script, Run, log_exception, mail
from VSS import Date
from VSS.path import Path, listdir, glob
from VSS.utils import PropertyDict
import openerplib

SOURCE = Path('/var/fis/')
ARCHIVE = Path('/var/openerp/archive/shipping/')
USER_PW_DB = Path('/etc/openerp/credentials')

execfile(USER_PW)

OE = PropertyDict()

module = {
    'incoming': 'F65',
    'outgoing': 'F33',
    'carrier':  'F27',
    }

def update_order(values):
    local_contacts = values.pop('local_contact', None)
    if local_contacts is not None:
        local_contacts = oe.res_users.search_read(fields=['id'], domain=[('login','in',local_contacts)])
        local_contact_ids = list(local_contacts.values())
        values.local_contact_ids = [(6, 0, local_contact_ids)]
    partner_xmlid = values.pop('partner_xmlid', None)
    if partner_xmlid is not None:
        partner_xmlid = OE.res_partner.search_read(fields=['id'], domain=[('module','=',module[values.direction]),('xml_id','=',values.partner_xmlid)])
        partner_id = list(partner_xmlid.values())[0]
        values.partner_id = partner_id
    carrier_xmlid = values.pop('carrier_xmlid', None)
    if carrier_xmlid is not None:
        carrier_xmlid = OE.res_partner.search_read(fields=['id'], domain=[('module','=',module['carrier']),('xml_id','=',values.carrier_xmlid)])
        carrier_id = list(carrier_xmlid.values())[0]
        values.carrier_id = carrier_id
    appt = values.pop('appointment_date', None)
    if appt is not None:
        values.appointment_date = Date.fromymd(appt)
    direction = values.get('direction')
    if direction == 'incoming':
        values.job_title = values.preposition = values.partner_source_document_type = 'purchasing'
    elif direction == 'outgoing':
        values.job_title = values.preposition = values.partner_source_document_type = 'sales'
    orders = OE.fnx_shipping.search_read(fields=['id', 'appt_confirmed', 'state'], domain=[('local_source_document','=',values.local_source_document)])
    print orders
    order = None
    for order in orders.values():
        break
    if not order:
        values.state = 'draft'
    elif values.pallets and order['state'] not in ('checked_in', 'complete', 'cancelled'):
        values.state = 'ready'
    if not order:
        OE.fnx_shipping.create(values)
    else:
        OE.fnx_shipping.write([order['id']], values)

@Script(
        file_to_process=('order to add/update in system', ),
        hostname=('host where OpenERP instance is running', ),
        db=('database to use', ),
        user=('login name to use', ),
        password=('password for login name', ),
        )
def main(file_to_process='', hostname='localhost', db=DB, user=USER, password=PW):
    if file_to_process:
        files = [file_to_process]
    else:
        files = [SOURCE/f for f in SOURCE.listdir() if f != 'order_template']

    OE.conn = conn = openerplib.get_connection(hostname='localhost', database=db, login=user, password=password)
    OE.res_partner = conn.get_model('res.partner')
    OE.res_users = conn.get_model('res.users')
    OE.fnx_shipping = conn.get_model('fnx.shipping')

    retry = []
    failed = []
    for file in files:
        try:
            g = {}
            execfile(file, g)
            order = PropertyDict(g['order'])
            update_order(order)
        except Exception:
            log_exception()
            retry.append(file)
    if retry:
        time.sleep(5)
        for file in retry:
            try:
                g = {}
                execfile(file, g)
                order = PropertyDict(g['order'])
                update_order(order)
            except Exception:
                log_exception()
                failed.append(file)
    if failed:
        raise Exception("Unable to process orders: %r" % ', '.join(failed))

if __name__ == '__main__':
    Run()
