#!/usr/bin/env python

from os import stat
from pwd import getpwuid
from scription import Script, Run, log_exception, mail
from VSS import Date
from VSS.path import Path, listdir, glob
from VSS.utils import PropertyDict
import openerplib
import shutil
import time

SOURCE = Path('/var/fis/')
ARCHIVE = Path('/var/openerp/archive/shipping/')
USER_PW_DB = Path('/etc/openerp/credentials')

execfile(USER_PW_DB)

OE = PropertyDict()

module = {
    'incoming': 'F65',
    'outgoing': 'F33',
    'carrier':  'F27',
    }

def archive(src_file, dest=ARCHIVE):
    existing = glob(dest/src_file+'*')
    src_file = Path(src_file)
    if not existing:
        dst_file = src_file.filename + '_01'
    else:
        existing.sort()
        dst_file, count = existing[-1].split('_')
        count = int(count) + 1
        dst_file += '_%02d' % count
    shutil.move(src_file, dest/dst_file)

def get_order(order):
    g = {}
    execfile(order, g)
    result = PropertyDict(g['order'])
    #result.user = getpwuid(stat(order).st_uid).pw_name
    return result

def update_order(values):
    print values
    local_contacts = values.pop('local_contact', None)
    #local_contacts = values.get('local_contact', None)
    if local_contacts is not None:
        if 'sysadmin' in local_contacts:
            local_contacts.append('admin')
        records = OE.res_users.search_read(fields=['id'], domain=[('login','in',local_contacts)])
        #local_contact_ids = [d['id'] for d in local_contacts]
        values.local_contact_ids = [lc['id'] for lc in records]
    partner_xmlid = values.pop('partner_xmlid', None)
    #partner_xmlid = values.get('partner_xmlid', None)
    if partner_xmlid is not None:
        records = OE.res_partner.search_read(fields=['id', 'module', 'xml_id'], domain=[('module','=',module[values.direction]),('xml_id','=',partner_xmlid)])
        if not records:
            raise ValueError('unable to find partner %r' % partner_xmlid)
        partner_id = records[0]['id']
        values.partner_id = partner_id
    carrier_xmlid = values.pop('carrier_xmlid', None)
    #carrier_xmlid = values.get('carrier_xmlid', None)
    print repr(carrier_xmlid)
    if carrier_xmlid not in ('99', None):
        print 'looking for carrier', carrier_xmlid
        records = OE.res_partner.search_read(fields=['id'], domain=[('module','=',module['carrier']),('xml_id','=',carrier_xmlid)])
        if not records:
            raise ValueError('unable to find carrier %r' % carrier_xmlid)
        carrier_id = records[0]['id']
        values.carrier_id = carrier_id
    direction = values.get('direction')
    if direction == 'incoming':
        values.job_title = values.preposition = values.partner_source_document_type = 'purchasing'
    elif direction == 'outgoing':
        values.job_title = values.preposition = values.partner_source_document_type = 'sales'
    if 'cartons' in values:
        values.cartons = int(values.cartons) or False
    if 'pallets' in values:
        values.pallets = int(values.pallets) or False
    if 'weight' in values:
        values.weight = float(values.weight) or False
    orders = OE.fnx_shipping.search_read(fields=['id', 'appt_confirmed', 'state'], domain=[('local_source_document','=',values.local_source_document)])
    order = None
    for order in orders:
        break
    if not order:
        values.state = 'draft'
    elif 'pallets' in values and values.pallets:
        if order['state'] in ('checked_in', 'complete', 'cancelled'):
            pass
        elif order['state'] == 'scheduled':
            values.state = 'ready'
        else:
            values.state = 'appt'
    #if values.state: order['state'] == values.state
    login = values.pop('user', None)
    if login is not None:
        records = OE.res_users.search_read(fields=['id'], domain=[('login','=',login)])
        values.user_id = records[0]['id']
    if not order:
        OE.fnx_shipping.create(dict(values))
    else:
        OE.fnx_shipping.write([order['id']], dict(values))

@Script(
        file_to_process=('order to add/update in system', ),
        hostname=('host where OpenERP instance is running', ),
        db=('database to use', ),
        user=('login name to use', ),
        password=('password for login name', ),
        )
def main(file_to_process='', hostname='localhost', db=DB, user=USER, password=PW):
    if file_to_process:
        files = [file_to_process]
    else:
        files = [SOURCE/f for f in SOURCE.listdir() if f != 'order_template']
    #
    print files
    #
    OE.conn = conn = openerplib.get_connection(hostname='localhost', database=db, login=user, password=password)
    OE.res_partner = conn.get_model('res.partner')
    OE.res_users = conn.get_model('res.users')
    OE.fnx_shipping = conn.get_model('fnx.sr.shipping')
    #
    retry = []
    failed = []
    for group in ((files, retry), (retry, failed)):
        time.sleep(5)
        trying, failing = group
        for file in trying:
            try:
                order = get_order(file)
                #import pdb; pdb.set_trace()
                update_order(order)
                archive(file)
            except Exception:
                log_exception()
                failing.append(file)
    if failed:
        raise Exception("Unable to process orders: %r" % ', '.join(failed))

if __name__ == '__main__':
    Run()

